### ISSUE TITLE
About Chakra

### ISSUE THREAD

**Issue by s8321414** [linux-taiwan/arch.linux.org.tw#27]
雖然Chakra現在仍在使用Arch的部份工具，不過應該不算是基於Arch的distro了?雖然這樣，那段文字還是要想想怎麼改會比較好......

**Comment by hiroshiyui** [comment]
@s8321414 Patches welcome! :smile_cat:

**Comment by hiroshiyui** [comment]
已經去掉「Arch 衍生版本」一節。

**Comment by s8321414** [comment]
:smile:
