### ISSUE TITLE
網站改用 WordPress 或 Drupal 架設

### ISSUE THREAD

**Issue by hiroshiyui** [linux-taiwan/arch.linux.org.tw#51]
改用更使用者友善的 CMS 來做，現在這種作法根本反人類，爭取不到 novice users，行不通。

另外開一個 branch 來做這張的 Ansible playbooks。

**Comment by hiroshiyui** [comment]
先用 WordPress 看看。

**Comment by hiroshiyui** [comment]
@Brli 徵求一下您的意見？

**Comment by Brli** [comment]
- 模板本身目前應該沒有大改的需求吧？
- Wordpress 必然要動到資料庫與 php 動態網頁的部份，這些東西 Github Page 好像沒有支援（目前只有基本的 ruby aka. jekyll 與靜態網頁）
- 文章用 markdown 形式寫，對於習慣用編輯器的人來講還蠻方便的，不需要特地另外做使用者管理（作者、留言等登入界面）
- 我也覺得反人類，但是反人類的部份目前看起來已經有高人幫忙搞定了，剩下就是人類的部份了（？）
- Jekyll 本身沒有升級問題，而且反正是純靜態，後端也是 github 在管，不至於出大錯，用 git 也方便回溯

**Comment by hiroshiyui** [comment]
這個網站從來都不是架在 Github Pages 上。

`反人類的部份目前看起來已經有高人幫忙搞定了` ← 哪位？

這個網站一直以來都是我在維護新聞翻譯，有時候事情一忙，新聞變舊聞，也自然放生了。除此之外，它也沒有盡到一個社群入口的功能。論引介新知，論社群交流，它都完全不及格，我想了想，就是因為內容的貢獻方式太曲折，除了引入一個比較 user friendly 的 CMS 來消除這個障礙，技術面我實在想不到有什麼方法可以再施力。

**Comment by Brli** [comment]
咦咦？！我以為是 CNAME redirection 而已…sorry
嗯…可以想見很少人發新聞翻譯稿…我以為是因為大家都讀原文去了
（有想要幫忙發文，只是看好像認識的 Archer 大大都沒反應，就不想獻醜了）
`← 哪位？` 就，讓網頁看起來像現在這樣子的大大們

**Comment by hiroshiyui** [comment]
`讓網頁看起來像現在這樣子的大大們` 您可以看一下 commit logs 大概就知道我所面臨的處境。

**Comment by Brli** [comment]
`您可以看一下 commit logs 大概就知道我所面臨的處境。` 非常可以理解 😢

**Comment by hiroshiyui** [comment]
昨晚想了一下，決定這張票先暫緩。結構性問題不是套用一個 CMS 就能解決的。

**Comment by hiroshiyui** [comment]
路線調整：

- 編纂 Arch Linux 台式中文手冊
- 架設論壇，採用 [Discourse](http://www.discourse.org/) 或 [Flarum](http://flarum.org/)

另外再開票來做。這張先放著，一週內沒有什麼其他意見的話再關掉。

**Comment by Brli** [comment]
Discourse [看來](https://github.com/discourse/discourse/blob/master/docs/INSTALL.md)是用 Docker 解

Flarum 是 PHP-based，架設容易，但是感覺維護不簡單

**Comment by hiroshiyui** [comment]
再租一台 VPS 來架論壇，這張關掉。
